# Generated by Django 5.2.17 on 2026-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='location',
            new_name='land_location',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='password',
        ),
        migrations.AddField(
            model_name='farmer',
            name='field_type',
            field=models.CharField(default='Not provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='major_crop',
            field=models.CharField(default='Not provided', max_length=100),
            preserve_default=False,
        ),
    ]
