# Generated by Django 5.2.17 on 2026-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_farmer_land_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='work_type',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='location',
            new_name='village',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='password',
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
