# Generated by Django 5.2.17 on 2026-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_work_type_worker_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
