# Generated by Django 5.2.17 on 2026-08-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_bookings', to='users.worker')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'worker'), name='unique_job_worker')],
            },
        ),
    ]
